#

FROM d_eclipse:isuper3

ENV A_USER=dd
ENV USERID=33747

RUN adduser --disabled-password --quiet --gecos '' --ingroup users -u $USERID $A_USER \
 && echo "$A_USER ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user \
 && chmod 0440 /etc/sudoers.d/user \
 && chown root:root /usr/bin/sudo && chmod 4755 /usr/bin/sudo

USER $A_USER
WORKDIR /home/$A_USER


