#FROM python:3.5-slim
FROM python:3.5
#FROM python:2.7.11

MAINTAINER dnaelam@gmail.com

ENV CORPORA brown

RUN pip install --upgrade pip \
 && pip install -U nltk numpy \
 && python -m nltk.downloader $CORPORA


